const dataobj = [
  {
    pageMst_ID: "1",
    pageMst_ITEM: "IT General Controls",
    pageMst_SLUG: "it-general-controls",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "1",
    POLICY_ID: "1",
    ITEM_ID: "1",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "18",
        pageMst_ITEM: "ITGC Dashboard",
        pageMst_SLUG: "itgc-dashboard",
        pageMst_HIERARCHY: "1",
        pageMst_IS_ACTIVE: "Y",
        ID: "18",
        POLICY_ID: "1",
        ITEM_ID: "18",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "19",
        pageMst_ITEM: "ITGC Selection",
        pageMst_SLUG: "itgc-selection",
        pageMst_HIERARCHY: "1",
        pageMst_IS_ACTIVE: "Y",
        ID: "19",
        POLICY_ID: "1",
        ITEM_ID: "19",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "65",
        pageMst_ITEM: "ITGC Subjective Controls",
        pageMst_SLUG: "itgc-subjective-controls",
        pageMst_HIERARCHY: "1",
        pageMst_IS_ACTIVE: "Y",
        ID: "65",
        POLICY_ID: "1",
        ITEM_ID: "65",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "2",
    pageMst_ITEM: "Automated Business Controls",
    pageMst_SLUG: "automated-business-controls",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "2",
    POLICY_ID: "1",
    ITEM_ID: "2",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "20",
        pageMst_ITEM: "ABC Dashboard",
        pageMst_SLUG: "abc-dashboard",
        pageMst_HIERARCHY: "2",
        pageMst_IS_ACTIVE: "Y",
        ID: "20",
        POLICY_ID: "1",
        ITEM_ID: "20",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "21",
        pageMst_ITEM: "ABC Selection",
        pageMst_SLUG: "abc-selection",
        pageMst_HIERARCHY: "2",
        pageMst_IS_ACTIVE: "Y",
        ID: "21",
        POLICY_ID: "1",
        ITEM_ID: "21",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "3",
    pageMst_ITEM: "Segragation of Duties",
    pageMst_SLUG: "segragation-of-duties",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "3",
    POLICY_ID: "1",
    ITEM_ID: "3",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
  },
  {
    pageMst_ID: "4",
    pageMst_ITEM: "iRM Setup & Admin",
    pageMst_SLUG: "irm-setup-admin",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "4",
    POLICY_ID: "1",
    ITEM_ID: "4",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "14",
        pageMst_ITEM: "iRM - Register New User",
        pageMst_SLUG: "irm-register-new-user",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "14",
        POLICY_ID: "1",
        ITEM_ID: "14",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.224Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "16",
        pageMst_ITEM: "iRM - Common Master Data Setup",
        pageMst_SLUG: "irm-common-master-data-setup",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "16",
        POLICY_ID: "1",
        ITEM_ID: "16",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "17",
        pageMst_ITEM: "iRM - Permission Management",
        pageMst_SLUG: "irm-permission-management",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "17",
        POLICY_ID: "1",
        ITEM_ID: "17",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "38",
        pageMst_ITEM: "Admin - dashboard",
        pageMst_SLUG: "admin-dashboard",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "38",
        POLICY_ID: "1",
        ITEM_ID: "38",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "39",
        pageMst_ITEM: "Administrative - Audit",
        pageMst_SLUG: "administrative-audit",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "39",
        POLICY_ID: "1",
        ITEM_ID: "39",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "52",
        pageMst_ITEM: "User - Authentication",
        pageMst_SLUG: "user-authentication",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "52",
        POLICY_ID: "1",
        ITEM_ID: "52",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "61",
        pageMst_ITEM: "iRM - Aliasing",
        pageMst_SLUG: "irm-aliasing",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "61",
        POLICY_ID: "1",
        ITEM_ID: "61",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "68",
        pageMst_ITEM: "Configuration",
        pageMst_SLUG: "configuration",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "68",
        POLICY_ID: "1",
        ITEM_ID: "68",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "69",
        pageMst_ITEM: "iRM - User Permission Management",
        pageMst_SLUG: "irm-user-permission-management",
        pageMst_HIERARCHY: "4",
        pageMst_IS_ACTIVE: "Y",
        ID: "69",
        POLICY_ID: "1",
        ITEM_ID: "69",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "5",
    pageMst_ITEM: "Default",
    pageMst_SLUG: "default",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "5",
    POLICY_ID: "1",
    ITEM_ID: "5",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
  },
  {
    pageMst_ID: "6",
    pageMst_ITEM: "iMatrix",
    pageMst_SLUG: "imatrix",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "6",
    POLICY_ID: "1",
    ITEM_ID: "6",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "15",
        pageMst_ITEM: "iRM - Data Sync",
        pageMst_SLUG: "irm-data-sync",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "15",
        POLICY_ID: "1",
        ITEM_ID: "15",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "22",
        pageMst_ITEM: "SOD Dashboard",
        pageMst_SLUG: "sod-dashboard",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "22",
        POLICY_ID: "1",
        ITEM_ID: "22",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "23",
        pageMst_ITEM: "SOD Selection",
        pageMst_SLUG: "sod-selection",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "23",
        POLICY_ID: "1",
        ITEM_ID: "23",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "24",
        pageMst_ITEM: "SOD Matrix",
        pageMst_SLUG: "sod-matrix",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "24",
        POLICY_ID: "1",
        ITEM_ID: "24",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "25",
        pageMst_ITEM: "SOD Details",
        pageMst_SLUG: "sod-details",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "25",
        POLICY_ID: "1",
        ITEM_ID: "25",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "26",
        pageMst_ITEM: "iMatrix - Simulation",
        pageMst_SLUG: "imatrix-simulation",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "26",
        POLICY_ID: "1",
        ITEM_ID: "26",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "27",
        pageMst_ITEM: "iMatrix - Simulation Log",
        pageMst_SLUG: "imatrix-simulation-log",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "27",
        POLICY_ID: "1",
        ITEM_ID: "27",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "34",
        pageMst_ITEM: "iMatrix - Overview",
        pageMst_SLUG: "imatrix-overview",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "34",
        POLICY_ID: "1",
        ITEM_ID: "34",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "36",
        pageMst_ITEM: "iMatrix - Role Simulation Dashboard",
        pageMst_SLUG: "imatrix-role-simulation-dashboard",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "36",
        POLICY_ID: "1",
        ITEM_ID: "36",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "37",
        pageMst_ITEM: "iMatrix - SOD Analysis Dashboard",
        pageMst_SLUG: "imatrix-sod-analysis-dashboard",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "37",
        POLICY_ID: "1",
        ITEM_ID: "37",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "40",
        pageMst_ITEM: "iMatrix - Sankey Dashboard",
        pageMst_SLUG: "imatrix-sankey-dashboard",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "40",
        POLICY_ID: "1",
        ITEM_ID: "40",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "43",
        pageMst_ITEM: "iMatrix - IRemediation",
        pageMst_SLUG: "imatrix-iremediation",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "43",
        POLICY_ID: "1",
        ITEM_ID: "43",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "44",
        pageMst_ITEM: "iMatrix - AmChart Sankey",
        pageMst_SLUG: "imatrix-amchart-sankey",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "44",
        POLICY_ID: "1",
        ITEM_ID: "44",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "53",
        pageMst_ITEM: "iRM - Report Data Sync",
        pageMst_SLUG: "irm-report-data-sync",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "53",
        POLICY_ID: "1",
        ITEM_ID: "53",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "59",
        pageMst_ITEM: "iMatrix - Generate Reports",
        pageMst_SLUG: "imatrix-generate-reports",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "59",
        POLICY_ID: "1",
        ITEM_ID: "59",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "60",
        pageMst_ITEM: "iMatrix - Role Inspector",
        pageMst_SLUG: "imatrix-role-inspector",
        pageMst_HIERARCHY: "6",
        pageMst_IS_ACTIVE: "Y",
        ID: "60",
        POLICY_ID: "1",
        ITEM_ID: "60",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "7",
    pageMst_ITEM: "iAssurance",
    pageMst_SLUG: "iassurance",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "7",
    POLICY_ID: "1",
    ITEM_ID: "7",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "28",
        pageMst_ITEM: "iAssurance - OverView",
        pageMst_SLUG: "iassurance-overview",
        pageMst_HIERARCHY: "7",
        pageMst_IS_ACTIVE: "Y",
        ID: "28",
        POLICY_ID: "1",
        ITEM_ID: "28",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "29",
        pageMst_ITEM: "iAssurance - Dashboard",
        pageMst_SLUG: "iassurance-dashboard",
        pageMst_HIERARCHY: "7",
        pageMst_IS_ACTIVE: "Y",
        ID: "29",
        POLICY_ID: "1",
        ITEM_ID: "29",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "30",
        pageMst_ITEM: "iAssurance - Completed Assessment",
        pageMst_SLUG: "iassurance-completed-assessment",
        pageMst_HIERARCHY: "7",
        pageMst_IS_ACTIVE: "Y",
        ID: "30",
        POLICY_ID: "1",
        ITEM_ID: "30",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "31",
        pageMst_ITEM: "iAssurance - Document Upload",
        pageMst_SLUG: "iassurance-document-upload",
        pageMst_HIERARCHY: "7",
        pageMst_IS_ACTIVE: "Y",
        ID: "31",
        POLICY_ID: "1",
        ITEM_ID: "31",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "32",
        pageMst_ITEM: "iAssurance - Reporting",
        pageMst_SLUG: "iassurance-reporting",
        pageMst_HIERARCHY: "7",
        pageMst_IS_ACTIVE: "Y",
        ID: "32",
        POLICY_ID: "1",
        ITEM_ID: "32",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "33",
        pageMst_ITEM: "iAssurance - Selection",
        pageMst_SLUG: "iassurance-selection",
        pageMst_HIERARCHY: "7",
        pageMst_IS_ACTIVE: "Y",
        ID: "33",
        POLICY_ID: "1",
        ITEM_ID: "33",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "35",
        pageMst_ITEM: "iAssurance - Assessment",
        pageMst_SLUG: "iassurance-assessment",
        pageMst_HIERARCHY: "7",
        pageMst_IS_ACTIVE: "Y",
        ID: "35",
        POLICY_ID: "1",
        ITEM_ID: "35",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "8",
    pageMst_ITEM: "ERM",
    pageMst_SLUG: "erm",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "8",
    POLICY_ID: "1",
    ITEM_ID: "8",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "41",
        pageMst_ITEM: "ERM - Assessment",
        pageMst_SLUG: "erm-assessment",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "41",
        POLICY_ID: "1",
        ITEM_ID: "41",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "42",
        pageMst_ITEM: "ERM - Master",
        pageMst_SLUG: "erm-master",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "42",
        POLICY_ID: "1",
        ITEM_ID: "42",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "45",
        pageMst_ITEM: "ERM - Key Tracker",
        pageMst_SLUG: "erm-key-tracker",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "45",
        POLICY_ID: "1",
        ITEM_ID: "45",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "46",
        pageMst_ITEM: "ERM - Hierarchy",
        pageMst_SLUG: "erm-hierarchy",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "46",
        POLICY_ID: "1",
        ITEM_ID: "46",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "47",
        pageMst_ITEM: "ERM - Master Clone",
        pageMst_SLUG: "erm-master-clone",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "47",
        POLICY_ID: "1",
        ITEM_ID: "47",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "48",
        pageMst_ITEM: "ERM - Master Hierarchy",
        pageMst_SLUG: "erm-master-hierarchy",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "48",
        POLICY_ID: "1",
        ITEM_ID: "48",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "49",
        pageMst_ITEM: "ERM - Master Clone Hierarchy",
        pageMst_SLUG: "erm-master-clone-hierarchy",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "49",
        POLICY_ID: "1",
        ITEM_ID: "49",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "50",
        pageMst_ITEM: "ERM - Master Group",
        pageMst_SLUG: "erm-master-group",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "50",
        POLICY_ID: "1",
        ITEM_ID: "50",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "51",
        pageMst_ITEM: "ERM - iSentiment",
        pageMst_SLUG: "erm-isentiment",
        pageMst_HIERARCHY: "8",
        pageMst_IS_ACTIVE: "Y",
        ID: "51",
        POLICY_ID: "1",
        ITEM_ID: "51",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "9",
    pageMst_ITEM: "iCertify",
    pageMst_SLUG: "icertify",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "9",
    POLICY_ID: "1",
    ITEM_ID: "9",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "54",
        pageMst_ITEM: "iCertify - Data Sync",
        pageMst_SLUG: "icertify-data-sync",
        pageMst_HIERARCHY: "9",
        pageMst_IS_ACTIVE: "Y",
        ID: "54",
        POLICY_ID: "1",
        ITEM_ID: "54",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "55",
        pageMst_ITEM: "iCertify - Certification Initiation",
        pageMst_SLUG: "icertify-certification-initiation",
        pageMst_HIERARCHY: "9",
        pageMst_IS_ACTIVE: "Y",
        ID: "55",
        POLICY_ID: "1",
        ITEM_ID: "55",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "56",
        pageMst_ITEM: "iCertify - Supervisor Dashboard",
        pageMst_SLUG: "icertify-supervisor-dashboard",
        pageMst_HIERARCHY: "9",
        pageMst_IS_ACTIVE: "Y",
        ID: "56",
        POLICY_ID: "1",
        ITEM_ID: "56",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "57",
        pageMst_ITEM: "iCertify - Overview",
        pageMst_SLUG: "icertify-overview",
        pageMst_HIERARCHY: "9",
        pageMst_IS_ACTIVE: "Y",
        ID: "57",
        POLICY_ID: "1",
        ITEM_ID: "57",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "58",
        pageMst_ITEM: "iCertify - Certification Tracker",
        pageMst_SLUG: "icertify-certification-tracker",
        pageMst_HIERARCHY: "9",
        pageMst_IS_ACTIVE: "Y",
        ID: "58",
        POLICY_ID: "1",
        ITEM_ID: "58",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "10",
    pageMst_ITEM: "iRM Super Admin",
    pageMst_SLUG: "irm-super-admin",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "10",
    POLICY_ID: "1",
    ITEM_ID: "10",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "13",
        pageMst_ITEM: "iRM - Register New Customer",
        pageMst_SLUG: "irm-register-new-customer",
        pageMst_HIERARCHY: "10",
        pageMst_IS_ACTIVE: "Y",
        ID: "13",
        POLICY_ID: "1",
        ITEM_ID: "13",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.224Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "11",
    pageMst_ITEM: "iAccess",
    pageMst_SLUG: "iaccess",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "11",
    POLICY_ID: "1",
    ITEM_ID: "11",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "62",
        pageMst_ITEM: "iAccess - iAccess",
        pageMst_SLUG: "iaccess-iaccess",
        pageMst_HIERARCHY: "11",
        pageMst_IS_ACTIVE: "Y",
        ID: "62",
        POLICY_ID: "1",
        ITEM_ID: "62",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "63",
        pageMst_ITEM: "iAccess - Authentication Workflow",
        pageMst_SLUG: "iaccess-authentication-workflow",
        pageMst_HIERARCHY: "11",
        pageMst_IS_ACTIVE: "Y",
        ID: "63",
        POLICY_ID: "1",
        ITEM_ID: "63",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "64",
        pageMst_ITEM: "iAccess - Persona Management",
        pageMst_SLUG: "iaccess-persona-management",
        pageMst_HIERARCHY: "11",
        pageMst_IS_ACTIVE: "Y",
        ID: "64",
        POLICY_ID: "1",
        ITEM_ID: "64",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "66",
        pageMst_ITEM: "iAccess - Form Management",
        pageMst_SLUG: "iaccess-form-management",
        pageMst_HIERARCHY: "11",
        pageMst_IS_ACTIVE: "Y",
        ID: "66",
        POLICY_ID: "1",
        ITEM_ID: "66",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
      {
        pageMst_ID: "67",
        pageMst_ITEM: "iAccess - Workflow Management",
        pageMst_SLUG: "iaccess-workflow-management",
        pageMst_HIERARCHY: "11",
        pageMst_IS_ACTIVE: "Y",
        ID: "67",
        POLICY_ID: "1",
        ITEM_ID: "67",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
  {
    pageMst_ID: "12",
    pageMst_ITEM: "Developer",
    pageMst_SLUG: "developer",
    pageMst_HIERARCHY: "0",
    pageMst_IS_ACTIVE: "Y",
    ID: "12",
    POLICY_ID: "1",
    ITEM_ID: "12",
    READOPS: "1",
    CREATEOPS: "1",
    UPDATEOPS: "1",
    DELETEOPS: "1",
    CRD_DATE: "2023-09-22T06:11:18.224Z",
    LAST_UPD_DATE: "2023-09-22T06:11:18.224Z",
    CRD_USR_ID: "1",
    UPD_USR_ID: "0",
    children: [
      {
        pageMst_ID: "70",
        pageMst_ITEM: "Dashboard Designer",
        pageMst_SLUG: "dashboard-designer",
        pageMst_HIERARCHY: "12",
        pageMst_IS_ACTIVE: "Y",
        ID: "70",
        POLICY_ID: "1",
        ITEM_ID: "70",
        READOPS: "1",
        CREATEOPS: "1",
        UPDATEOPS: "1",
        DELETEOPS: "1",
        CRD_DATE: "2023-09-22T06:11:18.225Z",
        LAST_UPD_DATE: "2023-09-22T06:11:18.225Z",
        CRD_USR_ID: "1",
        UPD_USR_ID: "0",
      },
    ],
  },
];

export default dataobj;
