export const templateData = {
  status: true,
  data: {
    phaseList: [
      {
        ID: "1",
        NAME: "Master Data",
        TYPE: "STEPPER",
        PARENT_ID: "0",
        DATA_TYPE: null,
        INPUT_FIELD: null,
        PLACE_HOLDER: null,
        CREATED_AT: "2024-02-01T10:16:26.809Z",
        UPDATED_AT: "2024-02-01T10:16:26.809Z",
      },
      {
        ID: "2",
        NAME: "Planning",
        TYPE: "STEPPER",
        PARENT_ID: "0",
        DATA_TYPE: null,
        INPUT_FIELD: null,
        PLACE_HOLDER: null,
        CREATED_AT: "2024-02-01T10:16:26.816Z",
        UPDATED_AT: "2024-02-01T10:16:26.816Z",
        children: [
          {
            ID: "3",
            NAME: "Create Audit Item",
            TYPE: "TAB",
            PARENT_ID: "2",
            DATA_TYPE: null,
            INPUT_FIELD: "create_audit_item",
            PLACE_HOLDER: null,
            CREATED_AT: "2024-02-01T10:16:26.821Z",
            UPDATED_AT: "2024-02-01T10:16:26.821Z",
            children: [
              {
                ID: "4",
                NAME: "Scope",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "scope",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.827Z",
                UPDATED_AT: "2024-02-01T10:16:26.827Z",
              },
              {
                ID: "5",
                NAME: "Audit title",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "audit_title",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.831Z",
                UPDATED_AT: "2024-02-01T10:16:26.831Z",
              },
              {
                ID: "6",
                NAME: "Audit Type",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "audit_type",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.835Z",
                UPDATED_AT: "2024-02-01T10:16:26.835Z",
              },
              {
                ID: "7",
                NAME: "Auditor(s)",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "auditor(s)",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.839Z",
                UPDATED_AT: "2024-02-01T10:16:26.839Z",
              },
              {
                ID: "8",
                NAME: "Planning Start Date",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "DATE",
                INPUT_FIELD: "planning_start_date",
                PLACE_HOLDER: "Date Selector",
                CREATED_AT: "2024-02-01T10:16:26.847Z",
                UPDATED_AT: "2024-02-01T10:16:26.847Z",
              },
              {
                ID: "9",
                NAME: "Audit Owner",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "audit_owner",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.850Z",
                UPDATED_AT: "2024-02-01T10:16:26.850Z",
              },
              {
                ID: "10",
                NAME: "Department / Area",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "department_area",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.854Z",
                UPDATED_AT: "2024-02-01T10:16:26.854Z",
              },
              {
                ID: "11",
                NAME: "Risk Assessment",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "risk_assessment",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.860Z",
                UPDATED_AT: "2024-02-01T10:16:26.860Z",
              },
              {
                ID: "12",
                NAME: "Planning End Date",
                TYPE: "INPUT",
                PARENT_ID: "3",
                DATA_TYPE: "DATE",
                INPUT_FIELD: "planning_end_date",
                PLACE_HOLDER: "Date Selector",
                CREATED_AT: "2024-02-01T10:16:26.864Z",
                UPDATED_AT: "2024-02-01T10:16:26.864Z",
              },
            ],
          },
          {
            ID: "13",
            NAME: "Create Audit Plans",
            TYPE: "TAB",
            PARENT_ID: "2",
            DATA_TYPE: null,
            INPUT_FIELD: null,
            PLACE_HOLDER: null,
            CREATED_AT: "2024-02-01T10:16:26.867Z",
            UPDATED_AT: "2024-02-01T10:16:26.867Z",
            children: [
              {
                ID: "14",
                NAME: "Title",
                TYPE: "INPUT",
                PARENT_ID: "13",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "title",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.871Z",
                UPDATED_AT: "2024-02-01T10:16:26.871Z",
              },
              {
                ID: "15",
                NAME: "Time Period",
                TYPE: "INPUT",
                PARENT_ID: "13",
                DATA_TYPE: "DATE",
                INPUT_FIELD: "time_period",
                PLACE_HOLDER: "Date Selector",
                CREATED_AT: "2024-02-01T10:16:26.876Z",
                UPDATED_AT: "2024-02-01T10:16:26.876Z",
              },
              {
                ID: "16",
                NAME: "Planned Effort",
                TYPE: "INPUT",
                PARENT_ID: "13",
                DATA_TYPE: "NUMBER",
                INPUT_FIELD: "planned_effort",
                PLACE_HOLDER: "Number Input",
                CREATED_AT: "2024-02-01T10:16:26.880Z",
                UPDATED_AT: "2024-02-01T10:16:26.880Z",
              },
              {
                ID: "17",
                NAME: "Financial Budget",
                TYPE: "INPUT",
                PARENT_ID: "13",
                DATA_TYPE: "NUMBER",
                INPUT_FIELD: "financial_budget",
                PLACE_HOLDER: "Number Input",
                CREATED_AT: "2024-02-01T10:16:26.884Z",
                UPDATED_AT: "2024-02-01T10:16:26.884Z",
              },
              {
                ID: "18",
                NAME: "Description",
                TYPE: "INPUT",
                PARENT_ID: "13",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "description",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.888Z",
                UPDATED_AT: "2024-02-01T10:16:26.888Z",
              },
              {
                ID: "19",
                NAME: "Status",
                TYPE: "INPUT",
                PARENT_ID: "13",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "status",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.892Z",
                UPDATED_AT: "2024-02-01T10:16:26.892Z",
              },
            ],
          },
          {
            ID: "20",
            NAME: "Create Audit",
            TYPE: "TAB",
            PARENT_ID: "2",
            DATA_TYPE: null,
            INPUT_FIELD: null,
            PLACE_HOLDER: null,
            CREATED_AT: "2024-02-01T10:16:26.897Z",
            UPDATED_AT: "2024-02-01T10:16:26.897Z",
            children: [
              {
                ID: "21",
                NAME: "Title",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "title",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.900Z",
                UPDATED_AT: "2024-02-01T10:16:26.900Z",
              },
              {
                ID: "22",
                NAME: "Audit Scope",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "audit_scope",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.904Z",
                UPDATED_AT: "2024-02-01T10:16:26.904Z",
              },
              {
                ID: "23",
                NAME: "Time Period",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "DATE",
                INPUT_FIELD: "time_period",
                PLACE_HOLDER: "Date Selector",
                CREATED_AT: "2024-02-01T10:16:26.909Z",
                UPDATED_AT: "2024-02-01T10:16:26.909Z",
              },
              {
                ID: "24",
                NAME: "Type",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "type",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.913Z",
                UPDATED_AT: "2024-02-01T10:16:26.913Z",
              },
              {
                ID: "25",
                NAME: "Group",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "group",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.916Z",
                UPDATED_AT: "2024-02-01T10:16:26.916Z",
              },
              {
                ID: "26",
                NAME: "Country / Region",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "country_region",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.919Z",
                UPDATED_AT: "2024-02-01T10:16:26.919Z",
              },
              {
                ID: "27",
                NAME: "Operating Units",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "operating_units",
                PLACE_HOLDER: "Number and Text Input",
                CREATED_AT: "2024-02-01T10:16:26.923Z",
                UPDATED_AT: "2024-02-01T10:16:26.923Z",
              },
              {
                ID: "28",
                NAME: "Estimated Efforts",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "NUMBER",
                INPUT_FIELD: "estimated_efforts",
                PLACE_HOLDER: "Number Input",
                CREATED_AT: "2024-02-01T10:16:26.929Z",
                UPDATED_AT: "2024-02-01T10:16:26.929Z",
              },
              {
                ID: "29",
                NAME: "Estimated Cost",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "NUMBER",
                INPUT_FIELD: "estimated_cost",
                PLACE_HOLDER: "Number Input",
                CREATED_AT: "2024-02-01T10:16:26.933Z",
                UPDATED_AT: "2024-02-01T10:16:26.933Z",
              },
              {
                ID: "30",
                NAME: "Tags",
                TYPE: "INPUT",
                PARENT_ID: "20",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "tags",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.937Z",
                UPDATED_AT: "2024-02-01T10:16:26.937Z",
              },
            ],
          },
          {
            ID: "31",
            NAME: "Initiate Audit",
            TYPE: "TAB",
            PARENT_ID: "2",
            DATA_TYPE: null,
            INPUT_FIELD: null,
            PLACE_HOLDER: null,
            CREATED_AT: "2024-02-01T10:16:26.941Z",
            UPDATED_AT: "2024-02-01T10:16:26.941Z",
          },
        ],
      },
      {
        ID: "32",
        NAME: "Resource Managment",
        TYPE: "STEPPER",
        PARENT_ID: "0",
        DATA_TYPE: null,
        INPUT_FIELD: null,
        PLACE_HOLDER: null,
        CREATED_AT: "2024-02-01T10:16:26.945Z",
        UPDATED_AT: "2024-02-01T10:16:26.945Z",
      },
      {
        ID: "33",
        NAME: "Preparation",
        TYPE: "STEPPER",
        PARENT_ID: "0",
        DATA_TYPE: null,
        INPUT_FIELD: null,
        PLACE_HOLDER: null,
        CREATED_AT: "2024-02-01T10:16:26.949Z",
        UPDATED_AT: "2024-02-01T10:16:26.949Z",
        children: [
          {
            ID: "34",
            NAME: "Background Information",
            TYPE: "TAB",
            PARENT_ID: "33",
            DATA_TYPE: null,
            INPUT_FIELD: null,
            PLACE_HOLDER: null,
            CREATED_AT: "2024-02-01T10:16:26.952Z",
            UPDATED_AT: "2024-02-01T10:16:26.952Z",
            children: [
              {
                ID: "35",
                NAME: "Background Information",
                TYPE: "INPUT",
                PARENT_ID: "34",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "background_information",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.956Z",
                UPDATED_AT: "2024-02-01T10:16:26.956Z",
              },
              {
                ID: "36",
                NAME: "Root Cause Analysis",
                TYPE: "INPUT",
                PARENT_ID: "34",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "root_cause_analysis",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.962Z",
                UPDATED_AT: "2024-02-01T10:16:26.962Z",
              },
              {
                ID: "37",
                NAME: "Impact Description",
                TYPE: "INPUT",
                PARENT_ID: "34",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "impact_description",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.966Z",
                UPDATED_AT: "2024-02-01T10:16:26.966Z",
              },
              {
                ID: "38",
                NAME: "Target Date",
                TYPE: "INPUT",
                PARENT_ID: "34",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "target_date",
                PLACE_HOLDER: "Date Selector",
                CREATED_AT: "2024-02-01T10:16:26.969Z",
                UPDATED_AT: "2024-02-01T10:16:26.969Z",
              },
              {
                ID: "39",
                NAME: "Audit Programme",
                TYPE: "INPUT",
                PARENT_ID: "34",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "audit_programme",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.972Z",
                UPDATED_AT: "2024-02-01T10:16:26.972Z",
              },
              {
                ID: "40",
                NAME: "Process Owner",
                TYPE: "INPUT",
                PARENT_ID: "34",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "process_owner",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.975Z",
                UPDATED_AT: "2024-02-01T10:16:26.975Z",
              },
              {
                ID: "41",
                NAME: "Audit Status",
                TYPE: "INPUT",
                PARENT_ID: "34",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "audit_status",
                PLACE_HOLDER: "Defult Sub Text",
                CREATED_AT: "2024-02-01T10:16:26.979Z",
                UPDATED_AT: "2024-02-01T10:16:26.979Z",
              },
            ],
          },
        ],
      },
      {
        ID: "42",
        NAME: "Execution",
        TYPE: "STEPPER",
        PARENT_ID: "0",
        DATA_TYPE: null,
        INPUT_FIELD: null,
        PLACE_HOLDER: null,
        CREATED_AT: "2024-02-01T10:16:26.983Z",
        UPDATED_AT: "2024-02-01T10:16:26.983Z",
        children: [
          {
            ID: "43",
            NAME: "Audit Execution Details",
            TYPE: "TAB",
            PARENT_ID: "42",
            DATA_TYPE: null,
            INPUT_FIELD: null,
            PLACE_HOLDER: null,
            CREATED_AT: "2024-02-01T10:16:26.986Z",
            UPDATED_AT: "2024-02-01T10:16:26.986Z",
            children: [
              {
                ID: "44",
                NAME: "Procedure Checklist",
                TYPE: "INPUT",
                PARENT_ID: "43",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "procedure_checklist",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.990Z",
                UPDATED_AT: "2024-02-01T10:16:26.990Z",
              },
              {
                ID: "45",
                NAME: "Findings",
                TYPE: "INPUT",
                PARENT_ID: "43",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "findings",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.995Z",
                UPDATED_AT: "2024-02-01T10:16:26.995Z",
              },
              {
                ID: "46",
                NAME: "Interview Summaries",
                TYPE: "INPUT",
                PARENT_ID: "43",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "interview_summaries",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:26.999Z",
                UPDATED_AT: "2024-02-01T10:16:26.999Z",
              },
              {
                ID: "47",
                NAME: "Progress Note",
                TYPE: "INPUT",
                PARENT_ID: "43",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "progress_note",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.002Z",
                UPDATED_AT: "2024-02-01T10:16:27.002Z",
              },
              {
                ID: "48",
                NAME: "Execution Title",
                TYPE: "INPUT",
                PARENT_ID: "43",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "execution_title",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.005Z",
                UPDATED_AT: "2024-02-01T10:16:27.005Z",
              },
              {
                ID: "49",
                NAME: "Evidence Attachment",
                TYPE: "INPUT",
                PARENT_ID: "43",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "evidence_attachment",
                PLACE_HOLDER: "File Upload",
                CREATED_AT: "2024-02-01T10:16:27.010Z",
                UPDATED_AT: "2024-02-01T10:16:27.010Z",
              },
              {
                ID: "50",
                NAME: "Interviews",
                TYPE: "INPUT",
                PARENT_ID: "43",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "interviews",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.013Z",
                UPDATED_AT: "2024-02-01T10:16:27.013Z",
              },
            ],
          },
        ],
      },
      {
        ID: "51",
        NAME: "Repoting",
        TYPE: "STEPPER",
        PARENT_ID: "0",
        DATA_TYPE: null,
        INPUT_FIELD: null,
        PLACE_HOLDER: null,
        CREATED_AT: "2024-02-01T10:16:27.016Z",
        UPDATED_AT: "2024-02-01T10:16:27.016Z",
        children: [
          {
            ID: "52",
            NAME: "Audit Reorting Details",
            TYPE: "TAB",
            PARENT_ID: "51",
            DATA_TYPE: null,
            INPUT_FIELD: null,
            PLACE_HOLDER: null,
            CREATED_AT: "2024-02-01T10:16:27.020Z",
            UPDATED_AT: "2024-02-01T10:16:27.020Z",
            children: [
              {
                ID: "53",
                NAME: "Draft Report",
                TYPE: "INPUT",
                PARENT_ID: "52",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "draft_report",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.025Z",
                UPDATED_AT: "2024-02-01T10:16:27.025Z",
              },
              {
                ID: "54",
                NAME: "Recommendation",
                TYPE: "INPUT",
                PARENT_ID: "52",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "recommendation",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.029Z",
                UPDATED_AT: "2024-02-01T10:16:27.029Z",
              },
              {
                ID: "55",
                NAME: "Management Response",
                TYPE: "INPUT",
                PARENT_ID: "52",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "management_response",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.032Z",
                UPDATED_AT: "2024-02-01T10:16:27.032Z",
              },
              {
                ID: "56",
                NAME: "Reviewer Note",
                TYPE: "INPUT",
                PARENT_ID: "52",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "reviewer_note",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.035Z",
                UPDATED_AT: "2024-02-01T10:16:27.035Z",
              },
              {
                ID: "57",
                NAME: "Root Cause",
                TYPE: "INPUT",
                PARENT_ID: "52",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "root_cause",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.039Z",
                UPDATED_AT: "2024-02-01T10:16:27.039Z",
              },
              {
                ID: "58",
                NAME: "Impact In Reporting",
                TYPE: "INPUT",
                PARENT_ID: "52",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "impact_in_reporting",
                PLACE_HOLDER: "File Upload",
                CREATED_AT: "2024-02-01T10:16:27.043Z",
                UPDATED_AT: "2024-02-01T10:16:27.043Z",
              },
              {
                ID: "59",
                NAME: "Attach Final Report",
                TYPE: "INPUT",
                PARENT_ID: "52",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "attach_final_report",
                PLACE_HOLDER: "File Upload",
                CREATED_AT: "2024-02-01T10:16:27.047Z",
                UPDATED_AT: "2024-02-01T10:16:27.047Z",
              },
            ],
          },
        ],
      },
      {
        ID: "60",
        NAME: "Follow Up",
        TYPE: "STEPPER",
        PARENT_ID: "0",
        DATA_TYPE: null,
        INPUT_FIELD: null,
        PLACE_HOLDER: null,
        CREATED_AT: "2024-02-01T10:16:27.049Z",
        UPDATED_AT: "2024-02-01T10:16:27.049Z",
        children: [
          {
            ID: "61",
            NAME: "Audit Reorting Details",
            TYPE: "TAB",
            PARENT_ID: "60",
            DATA_TYPE: null,
            INPUT_FIELD: null,
            PLACE_HOLDER: null,
            CREATED_AT: "2024-02-01T10:16:27.053Z",
            UPDATED_AT: "2024-02-01T10:16:27.053Z",
            children: [
              {
                ID: "62",
                NAME: "Details Observation",
                TYPE: "INPUT",
                PARENT_ID: "61",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "details_observation",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.057Z",
                UPDATED_AT: "2024-02-01T10:16:27.057Z",
              },
              {
                ID: "63",
                NAME: "Root Cause",
                TYPE: "INPUT",
                PARENT_ID: "61",
                DATA_TYPE: "TEXT",
                INPUT_FIELD: "root_cause",
                PLACE_HOLDER: "Text Input",
                CREATED_AT: "2024-02-01T10:16:27.063Z",
                UPDATED_AT: "2024-02-01T10:16:27.063Z",
              },
            ],
          },
        ],
      },
    ],
  },
  message: "Phase List fetch Sucessfully",
  errors: [],
};